# Site settings
title: Abiel Almonte
email: abielalmonte.eng@gmail.com
description: >-
  Abiel Almonte's personal website and projects.
baseurl: ""
url: "https://abiel-almonte.github.io"
github_username: abiel-almonte

# Author info (used in layouts)
author:
  name: "Abiel Almonte"
  email: "abielalmonte.eng@gmail.com"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: page

# Build settings
markdown: kramdown
include: ['_pages']
plugins:
  - jekyll-feed
